# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20171228_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', upload_to='courses/%Y/%m', verbose_name='头像'),
        ),
    ]
