# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-24 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20180121_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=200, verbose_name='视频地址'),
        ),
    ]
