# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-21 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171212_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banner/%Y/%m', verbose_name='轮播图'),
        ),
    ]
